name: bci_device_sdk_example
version: 0.1.0+1
description: Demonstrates how to use the bci_device_sdk plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0" # test by 3.19.6

dependencies:
  flutter:
    sdk: flutter

  # comment this dependency if not use Crimson device
  libcmsn:
    version: 2.4.1
    hosted:
      name: libcmsn
      url: https://dart-pub.brainco.cn

  # comment this dependency if not use OxyZen device
  liboxyz:
    version: 1.26.0
    hosted:
      name: liboxyz
      url: https://dart-pub.brainco.cn

  flutter_utils:
    version: ^2.1.3
    hosted:
      name: flutter_utils
      url: https://dart-pub.brainco.cn

  fl_chart: ^0.66.1 # 0.66.0 from Flutter 3.16
  charts_flutter_new: ^0.12.0
  flutter_easyloading: ^3.0.5
  get: ^4.6.6 # 4.6.6 from Flutter 3.13
  flutter_switch: ^0.3.2
  app_settings: ^5.0.0
  shared_preferences: ^2.0.5
  cached_network_image: ^3.2.1
  path_provider: ^2.0.2
  json_annotation: ^4.0.1
  keyboard_actions: ^4.2.0
  group_button: ^5.0.1
  wakelock_plus: ^1.1.1
  url_launcher: ^6.1.12
  file_picker: ^5.3.3
  provider: ^6.0.5
  dropdown_button2: ^1.4.0

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
