name: bci_device_sdk_example
version: 0.0.1+1
description: Demonstrates how to use the bci_device_sdk plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  libcmsn:
    version: ^1.4.9
    hosted:
      name: libcmsn
      url: https://dart-pub.brainco.cn

  liboxyz:
    version: ^0.11.9
    hosted:
      name: liboxyz
      url: https://dart-pub.brainco.cn

  fl_chart: #">=0.62.0" #0.63.0
  charts_flutter_new:
  flutter_easyloading: ^3.0.5
  get: ^4.6.5
  flutter_switch: ^0.3.2
  app_settings: ">=4.2.0"
  shared_preferences: ^2.0.5
  cached_network_image: ^3.2.1
  path_provider: ^2.0.2
  json_annotation: ^4.0.1
  keyboard_actions: ^4.2.0
  group_button: ^5.0.1
  wakelock_plus: ^1.1.1
  package_info_plus: ^4.0.2

  aliyun_oss:
    version: ^0.0.1
    hosted:
      name: aliyun_oss
      url: https://dart-pub.brainco.cn

  flutter_utils:
    version: ^2.0.1
    hosted:
      name: flutter_utils
      url: https://dart-pub.brainco.cn

  url_launcher:
  file_picker:
  provider:
  dropdown_button2: ^1.4.0

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
